### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tuhaolam** [kashifrazzaqui/json-streamer#11]
Traceback (most recent call last):
  File "test_jsonstreamer.py", line 3, in <module>
    from jsonstreamer import JSONStreamer 
  File "/usr/local/lib/python2.7/dist-packages/jsonstreamer/__init__.py", line 9, in <module>
    from jsonstreamer.jsonstreamer import JSONStreamer, ObjectStreamer
  File "/usr/local/lib/python2.7/dist-packages/jsonstreamer/jsonstreamer.py", line 12, in <module>
    from again import events
  File "/usr/local/lib/python2.7/dist-packages/again/__init__.py", line 4, in <module>
    from .events import EventSource, AsyncEventSource
  File "/usr/local/lib/python2.7/dist-packages/again/events.py", line 49
    yield from each(*args, **kwargs)
             ^
SyntaxError: invalid syntax
python --version
Python 2.7.3

**Comment by sethwoodworth** [comment]
I think it's safe to assume that this library doesn't support python2.7

**Comment by kashifrazzaqui** [comment]
Sorry, it doesnt.
